//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeGaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_letters_history
    {
        public int id { get; set; }
        public int game_id { get; set; }
        public string letters { get; set; }
    
        public virtual game game { get; set; }
    }
}
