//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeGaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_words_history
    {
        public int gwh_id { get; set; }
        public int gwh_game_id { get; set; }
        public int gwh_player_id { get; set; }
        public int gwh_word_id { get; set; }
        public System.DateTime gwh_datetime { get; set; }
    
        public virtual game game { get; set; }
        public virtual player player { get; set; }
        public virtual word word { get; set; }
    }
}
