//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeGaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        public word()
        {
            this.game_words_history = new HashSet<game_words_history>();
        }
    
        public int id { get; set; }
        public string word1 { get; set; }
    
        public virtual ICollection<game_words_history> game_words_history { get; set; }
    }
}
